on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: ['ethereum', 'testnet']
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.network }}
      - run: |
          git fetch --unshallow
          git reset --hard origin/main
          git push --force
